name: Deploy
on:
  push:
    branches:
      - master
      - feature
jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint HTML
        run: echo "Linting HTML"
  docker-build:
    runs-on: ubuntu-latest
    needs: lint-html
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${{ github.ref_name }}-latest .
  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${{ github.ref_name }}-latest
  deploy-gh-page:
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
 
